'use client'

import { motion, useScroll, useTransform } from 'framer-motion'
import { useRef } from 'react'

const services = ['Pier & Beam House Leveling','Housing Raising','Tuck Pointing','Engineer Certification','Root Barrier Installation','Drainage & Soil Solutions']
const areas = ['Sugar Land','Fort Bend County','Cinco Ranch','Rosenberg','Katy','Missouri City','Pearland']

export default function Home(){
 const ref=useRef(null); const {scrollYProgress}=useScroll({target:ref,offset:['start start','end start']}); const scale=useTransform(scrollYProgress,[0,.7],[1,1.12]); const y=useTransform(scrollYProgress,[0,.7],[0,80])
 return <main ref={ref}>
  <nav><div className="logo"><span>STAR</span> TECHN</div><div className="navlinks"><a href="#services">Services</a><a href="#process">Process</a><a href="#reviews">Reviews</a><a href="#areas">Service Area</a></div><a className="navcta" href="tel:18324895484">Call 832.489.5484</a></nav>
  <section className="hero"><motion.div className="heroimage" style={{scale,y}}/><div className="shade"/><div className="heroContent"><p className="eyebrow">HOUSTON FOUNDATION SPECIALISTS · FAMILY OWNED</p><h1>THE FOUNDATION<br/><i>UNDERNEATH</i> IT ALL.</h1><p className="lead">Foundation repair and structural solutions for Houston-area homes, delivered with a straightforward process and engineer-certified expertise.</p><div className="actions"><a className="primary" href="tel:18324895484">REQUEST A FREE QUOTE <span>↗</span></a><a className="ghost" href="#services">Explore services ↓</a></div></div><div className="heroMeta"><span>01 — 06</span><span>FOUNDATION / REPAIR / HOUSTON TX</span></div></section>
  <section className="trust"><div><b>15+</b><span>YEARS EXPERIENCE</span></div><div><b>BBB</b><span>ACCREDITED BUSINESS</span></div><div><b>ES / EN</b><span>BILINGUAL SERVICE</span></div><div><b>✓</b><span>ENGINEER-CERTIFIED WORK</span></div></section>
  <section className="intro"><p className="eyebrow">01 / KNOW THE SIGNS</p><h2>Your house<br/><em>is talking.</em></h2><p className="bodycopy">Cracks in walls or flooring, sticking doors and windows, and uneven floors can be signs of foundation movement. Star Techn provides inspections and targeted foundation solutions based on the condition of your property.</p><div className="symptoms"><span>01 CRACKS</span><span>02 UNEVEN FLOORS</span><span>03 STICKING DOORS</span><span>04 WALL GAPS</span></div></section>
  <section id="services" className="services"><div className="sectionhead"><p className="eyebrow">02 / OUR EXPERTISE</p><h2>Built to <em>correct.</em></h2></div><div className="servicegrid">{services.map((s,i)=><motion.article key={s} whileHover={{y:-8}}><span>0{i+1}</span><h3>{s}</h3><p>Specialized foundation and structural services tailored to the conditions of your home.</p><a href="tel:18324895484">Request service ↗</a></motion.article>)}</div></section>
  <section id="process" className="process"><div><p className="eyebrow">03 / THE PROCESS</p><h2>Clear from<br/><em>day one.</em></h2></div><div className="steps">{[['01','Book','Choose a time for your consultation.'],['02','Schedule','Set the project date and scope of work.'],['03','Repair','Our team completes the assigned work.'],['04','Move forward','A straightforward path from concern to solution.']].map(x=><div className="step" key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
  <section className="statement"><p>FOUNDATION REPAIR SHOULD FEEL<br/><strong>LIKE A SOLUTION.</strong></p></section>
  <section id="reviews" className="reviews"><p className="eyebrow">04 / CUSTOMER VOICE</p><h2>See why<br/><em>Houston trusts.</em></h2><div className="review"><span>★ ★ ★ ★ ★</span><blockquote>Explore verified customer experiences, completed projects and the team’s approach before you schedule your consultation.</blockquote><a className="ghost" href="https://startexfoundationrepair.com/">View company site ↗</a></div></section>
  <section id="areas" className="areas"><div><p className="eyebrow">05 / WHERE WE WORK</p><h2>Houston<br/><em>& beyond.</em></h2></div><div className="arealist">{areas.map((a,i)=><span key={a}><small>0{i+1}</small>{a}</span>)}</div></section>
  <section className="cta"><p className="eyebrow">06 / TAKE THE FIRST STEP</p><h2>YOUR HOME<br/>DESERVES A <em>SOLID START.</em></h2><p>Talk with Star Techn about your foundation project and request a free quote.</p><a className="primary" href="tel:18324895484">CALL 832.489.5484 ↗</a></section>
  <footer><div className="logo"><span>STAR</span> TECHN</div><p>Foundation repair and structural solutions for Houston, Texas and surrounding communities.</p><a href="tel:18324895484">832.489.5484</a><small>© {new Date().getFullYear()} Star Techn Foundation Repair. All rights reserved.</small></footer>
 </main>
}